name: automatic commits daily
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: ${{ env.daily == '' }}
        env:
          daily_buff: 0
      - name: add and commit
        uses: EndBug/add-and-commit@v7.1.1
        with:
          remove: '${{env.daily_buff}}.pl'
      - name: update var
        id: update_var
        run: |
          echo "daily_buff={${{env.daily_buff}}+1}" >> $GITHUB_ENV          
