name: automatic commits daily
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "./files/${{ steps.vars.outputs.sha_short }}.pl"
          FILE_DATA: "#!/usr/bin/perl\r\nuse strict;\r\nuse warnings;\r\nprint '${{steps.vars.outputs.sha_short}}';"
      - name: add and commit
        uses: EndBug/add-and-commit@v7.1.1
        with:
          add: "./files/${{ steps.vars.outputs.sha_short }}.pl"   
